### ISSUE TITLE
datasets

### ISSUE THREAD

**Issue by leihaimei** [bhavesh907/Crop-Classification#1]
Dear author:
I am learning your this project. It help me a lot. But i can not understand somewhere in code because i can not download the datasets. Could you please share it again?
Thank you very much!

**Comment by neuranetz-AI** [comment]
Hi @leihaimei you can download the dataset from [Gdrive](https://drive.google.com/drive/folders/1go32yGsEoLkYQi48qVQoG7shDuTgfjf4?usp=sharing).

**Comment by bhavesh907** [comment]
Hi @leihaimei 

you can download the dataset from [Gdrive](https://drive.google.com/drive/folders/1go32yGsEoLkYQi48qVQoG7shDuTgfjf4?usp=sharing).
